### ISSUE TITLE
For the download as ZIP option, remove/strip anything defined in the .openshiftio folder

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/launchpad-addon#21]
When the user selects to download the project as a ZIP instead of forking, remove all the metadata for Continuous Delivery we keep in `.openshiftio/`

**Comment by gastaldi** [comment]
https://github.com/openshiftio/launchpad-addon/commit/8b0484f80ee1753fed932bdcb5db7600c78ca303

**Comment by gastaldi** [comment]
Fixed in https://github.com/openshiftio/launchpad-backend/commit/f1627b79bdf4cf4edd14568a6d5251c1f78e3135
