### ISSUE TITLE
Recursive clone behavior seems to have been lost

### ISSUE THREAD

**Issue by starksm64** [openshiftio/launchpad-addon#28]
When I tried downloading the wfswarm and vert.x secured boosters as zip files using my https://github.com/starksm64/booster-catalog, and I'm not seeing the sso submodule being included any longer:

[sstark@rhcsb ObsidianToaster]$ jar -tf booster-rest-http-secured-wildfly-swarm.zip 
booster-rest-http-secured-wildfly-swarm//
booster-rest-http-secured-wildfly-swarm/app/
booster-rest-http-secured-wildfly-swarm/app/pom.xml
booster-rest-http-secured-wildfly-swarm/app/src/
booster-rest-http-secured-wildfly-swarm/app/src/test/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/quickstart/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/quickstart/sso/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/quickstart/sso/GreetingServiceTest.java
booster-rest-http-secured-wildfly-swarm/app/src/main/
booster-rest-http-secured-wildfly-swarm/app/src/main/fabric8/
booster-rest-http-secured-wildfly-swarm/app/src/main/fabric8/svc.yml
booster-rest-http-secured-wildfly-swarm/app/src/main/fabric8/deployment.yml
booster-rest-http-secured-wildfly-swarm/app/src/main/fabric8/route.yml
booster-rest-http-secured-wildfly-swarm/app/src/main/webapp/
booster-rest-http-secured-wildfly-swarm/app/src/main/webapp/WEB-INF/
booster-rest-http-secured-wildfly-swarm/app/src/main/webapp/WEB-INF/web.xml
booster-rest-http-secured-wildfly-swarm/app/src/main/webapp/WEB-INF/keycloak.json
booster-rest-http-secured-wildfly-swarm/app/src/main/java/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/Greeting.java
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/GreetingController.java
booster-rest-http-secured-wildfly-swarm/.gitignore
booster-rest-http-secured-wildfly-swarm/pom.xml
booster-rest-http-secured-wildfly-swarm/README.md
booster-rest-http-secured-wildfly-swarm/LICENSE
[sstark@rhcsb ObsidianToaster]$ 

[sstark@rhcsb ObsidianToaster]$ jar -tf booster-rest-http-secured-vertx.zip
booster-rest-http-secured-vertx//
booster-rest-http-secured-vertx/app/
booster-rest-http-secured-vertx/app/pom.xml
booster-rest-http-secured-vertx/app/src/
booster-rest-http-secured-vertx/app/src/main/
booster-rest-http-secured-vertx/app/src/main/fabric8/
booster-rest-http-secured-vertx/app/src/main/fabric8/deploymentconfig.yaml
booster-rest-http-secured-vertx/app/src/main/fabric8/template.yml
booster-rest-http-secured-vertx/app/src/main/fabric8/route.yml
booster-rest-http-secured-vertx/app/src/main/resources/
booster-rest-http-secured-vertx/app/src/main/resources/webroot/
booster-rest-http-secured-vertx/app/src/main/resources/webroot/index.html
booster-rest-http-secured-vertx/app/src/main/resources/webroot/keycloak.js
booster-rest-http-secured-vertx/app/src/main/service.yml
booster-rest-http-secured-vertx/app/src/main/java/
booster-rest-http-secured-vertx/app/src/main/java/io/
booster-rest-http-secured-vertx/app/src/main/java/io/openshift/
booster-rest-http-secured-vertx/app/src/main/java/io/openshift/booster/
booster-rest-http-secured-vertx/app/src/main/java/io/openshift/booster/RestApplication.java
booster-rest-http-secured-vertx/app/src/main/java/io/openshift/booster/service/
booster-rest-http-secured-vertx/app/src/main/java/io/openshift/booster/service/Greeting.java
booster-rest-http-secured-vertx/app/src/test/
booster-rest-http-secured-vertx/app/src/test/resources/
booster-rest-http-secured-vertx/app/src/test/resources/arquillian.xml
booster-rest-http-secured-vertx/app/src/test/java/
booster-rest-http-secured-vertx/app/src/test/java/io/
booster-rest-http-secured-vertx/app/src/test/java/io/openshift/
booster-rest-http-secured-vertx/app/src/test/java/io/openshift/booster/
booster-rest-http-secured-vertx/app/src/test/java/io/openshift/booster/RestApplicationTest.java
booster-rest-http-secured-vertx/.gitignore
booster-rest-http-secured-vertx/pom.xml
booster-rest-http-secured-vertx/LICENSE-2.0.txt
booster-rest-http-secured-vertx/README.md
booster-rest-http-secured-vertx/.editorconfig
[sstark@rhcsb ObsidianToaster]$ 

Is there a problem with the gitRef I'm using?

[booster-catalog 634]$ cat rest-http-secured/vert.x/vertx-rest-http-secured-booster.yaml 
githubRepo: openshiftio-vertx-boosters/vertx-secured-http-booster
gitRef: 66283639fc65ffe14c1ce8d055a612b6a95d2d82

Seems to work:

[sstark@rhcsb ObsidianToaster]$ git clone --recursive https://github.com/openshiftio-vertx-boosters/vertx-secured-http-booster.git
Cloning into 'vertx-secured-http-booster'...
remote: Counting objects: 530, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 530 (delta 0), reused 0 (delta 0), pack-reused 526
Receiving objects: 100% (530/530), 110.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (190/190), done.
Submodule 'sso' (https://github.com/obsidian-toaster-quickstarts/redhat-sso) registered for path 'sso'
Cloning into 'sso'...
remote: Counting objects: 185, done.
remote: Total 185 (delta 0), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (185/185), 165.28 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
Submodule path 'sso': checked out 'cd9fbf0980a3930ca7da1f1814a040bf5b032e96'
[sstark@rhcsb ObsidianToaster]$ cd vertx-secured-http-booster/
[sstark@rhcsb vertx-secured-http-booster]$ git checkout 66283639fc65ffe14c1ce8d055a612b6a95d2d82
Note: checking out '66283639fc65ffe14c1ce8d055a612b6a95d2d82'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 6628363... Merge pull request #13 from starksm64/master
[sstark@rhcsb vertx-secured-http-booster]$ ls
app  Jenkinsfile  LICENSE-2.0.txt  pom.xml  README.md  sso
[sstark@rhcsb vertx-secured-http-booster]$ ls sso/
images  pom.xml  README.adoc  scripts  src
[sstark@rhcsb vertx-secured-http-booster]$

**Comment by gastaldi** [comment]
I can't reproduce it. Just tested with the latest master and I can see the sso/ directory inside the ZIP. Have you tried running Launchpad locally?

**Comment by starksm64** [comment]
This was using launchpad on minishift, but it was with it configured to
skip the OSO login because the front end was not working. Let me try it
again with the frontend fix.

**Comment by starksm64** [comment]
Using the current lanuchpad frontend I am getting the full contents in the zip download:

[sstark@sstark ObsidianToaster]$ jar -tf booster-rest-http-secured-wildfly-swarm.zip | grep sso
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/quickstart/sso/
booster-rest-http-secured-wildfly-swarm/app/src/test/java/org/obsidiantoaster/quickstart/sso/GreetingServiceTest.java
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/Greeting.java
booster-rest-http-secured-wildfly-swarm/app/src/main/java/org/obsidiantoaster/quickstart/sso/GreetingController.java
booster-rest-http-secured-wildfly-swarm/sso/
booster-rest-http-secured-wildfly-swarm/sso/src/
booster-rest-http-secured-wildfly-swarm/sso/src/main/
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/2-secret.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/secure-sso-route.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/sso-service.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/sso-route.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/1-secret.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/1-sa.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/template.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/sso-deploymentconfig.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/fabric8/secure-sso-service.yml
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/LoggingFilter.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/CommandArgs.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/authz/
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/authz/AuthzClient.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/authz/AccessToken.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/authz/Configuration.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/json/
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/json/JsonSerialization.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/json/SystemEnvProperties.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/json/StringPropertyReplacer.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/json/SystemPropertiesJsonParserFactory.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/Greeting.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/IGreeting.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/client/GreetingAuthzClient.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/util/
booster-rest-http-secured-wildfly-swarm/sso/src/main/java/util/EncodeJsonConfig.java
booster-rest-http-secured-wildfly-swarm/sso/src/main/resources/
booster-rest-http-secured-wildfly-swarm/sso/src/main/resources/master.json
booster-rest-http-secured-wildfly-swarm/sso/src/main/resources/keycloak.json
booster-rest-http-secured-wildfly-swarm/sso/src/main/resources/token_req_template.sh
booster-rest-http-secured-wildfly-swarm/sso/.gitignore
booster-rest-http-secured-wildfly-swarm/sso/README.adoc
booster-rest-http-secured-wildfly-swarm/sso/pom.xml
booster-rest-http-secured-wildfly-swarm/sso/images/
booster-rest-http-secured-wildfly-swarm/sso/images/Qmark.png
booster-rest-http-secured-wildfly-swarm/sso/images/OSOConsole.png
booster-rest-http-secured-wildfly-swarm/sso/images/OSOLogin.png
booster-rest-http-secured-wildfly-swarm/sso/scripts/
booster-rest-http-secured-wildfly-swarm/sso/scripts/token_req.py
[sstark@sstark ObsidianToaster]$
