### ISSUE TITLE
create the necessary wizard/steps in the new release that works like the old `io.openshift.launchpad.ui.booster.NewProjectWizard` class that OSIO is using

### ISSUE THREAD

**Issue by jstrachan** [openshiftio/launchpad-addon#44]
I just tried to upgrade to the new version 11 of the addon and its all very different now. See: https://github.com/openshiftio/launchpad-addon/issues/42#issuecomment-323749877

We were extending the `io.openshift.launchpad.ui.booster.NewProjectWizard` class and overriding it to provide additional validation; (we have separate steps to pick pipelines, OSIO spaces/projects, CI /CD stuff etc).

I wonder can we bring back a class which works about the same as the old way; that doesn't provide a picker of `Deployments` or anything - just lets us pick from a list of quickstarts in a single Wizard step and lets us override it to validate the project name. Then we can keep running on the latest / greatest launch-addon (and it avoids us having to refactor the catalog out into a shared library and whatnot - so it should have minimal impact on the LSIO codebase).

e.g. lets add a new wizard class for temporary use for OSIO - which works in the old way

**Comment by jstrachan** [comment]
@gastaldi so I was thinking we'd take the latest version of the old wizard class (from around 2.0.0.Alpha1 or later) and sizzle it to use the latest/greatest catalog service and see if we could get it working. Might be easiest for me to do it as I can be testing it inside OSIO as I hack on it

**Comment by jstrachan** [comment]
@gastaldi we may need to split it into 2 steps (pick mission then runtime maybe) - so may need tweaks in both OSIO and launchpad-addon

**Comment by gastaldi** [comment]
Ok, let's figure out what the necessary flow is needed first. Probably you won't be able to use our steps directly because some of them validate against mission-control

**Comment by gastaldi** [comment]
Sounds like a plan. Do you want to perform all these changes in the OSIO addon or do you need any changes in the launchpad-addon right now to support this?

**Comment by gastaldi** [comment]
Just pushed a change to launchpad-addon to decouple the wizard steps (https://github.com/openshiftio/launchpad-addon/commit/ddc8fc65045f696953cb0dcb9bb13b24bc795dcb). Now you can cherry-pick the steps that you want and build your own wizard flow

**Comment by jstrachan** [comment]
I was gonna try put this into the launchpadd-addon; so that it gets maintained as the catalog stuff changes and so that you can see clearly what we need
